version: "2.30.3"
services:
  non-code:
    build: 
      context: ./non_code
      dockerfile: ./Dockerfile.non_code
    ports:
      - "3000:3000"
    volumes:
      - ./non_code:/app:ro
  influxdb2:
    image: influxdb:2
    #ports:
    #  - 3000:3000
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: t0952254790
      DOCKER_INFLUXDB_INIT_PASSWORD: t19990914
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    volumes:
      - type: volume
        source: influxdb2-data
        target: /var/lib/influxdb2
      - type: volume
        source: influxdb2-config
        target: /etc/influxdb2
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.frontend
    ports:
      - "4000:4000"


volumes:
  influxdb2-data:
  influxdb2-config: